user_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :banks

  post "/banks/new" => "banks#create"

  get "/get_all_user_details" =>"banks#get_all_user_details"

  get "/view_my_profile" => "banks#view_my_profile"

  get "/block_users" => "banks#block_users"

  match "/change_user_status/:id" => "banks#change_user_status",:via => [:get,:post]

  match "/show_user_profile/assign_picture_to_user/:id" => "banks#assign_picture_to_user",:via => [:get,:post]

  root :to => redirect('/banks')

end

user_app/app/models/bank.rb
class Bank < ActiveRecord::Base
end

user_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

user_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

user_app/app/controllers/banks_controller.rb
class BanksController < ApplicationController
before_action :set_pinboard, only: [:show, :edit, :update, :destroy]


  def index
    @pin_properties = current_user.email
  end

  def show
    #@comments = @idea.comments.all
    #@comment = @idea.comments.build
  end

  def new
    @pin_properties = Bank.new
  end

  def edit
    if @pin_properties.user != current_user
      respond_to do |format|
        format.html { redirect_to pinboard_path, alert: 'You are not authorized to edit this pinboard.' }
        format.json { head :no_content }
      end
      return false
    end
  end

  def create
    @pin_property = Bank.new(pinboard_params)
     @pin_property.user = current_user

    respond_to do |format|
      if @pin_property.save
        format.html { 
          redirect_to pinboards_path, notice: 'PinProperty was successfully created.' 
        }
        format.json { render :show, status: :created, location: @pin_property }
      else
        format.html { render :new }
        format.json { render json: @pin_property.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_all_user_details
      @users = User.all - [User.find_by_email("admin@bitlasoft.com"),User.find_by_email(current_user.email)]
      render :template => "/pinboards/users_list" 
  end

def view_my_profile
  
end

def block_users
   @users = User.all - [User.find_by_email(current_user.email)]
   render :template => "/pinboards/block_users" 
end


def assign_picture_to_user
 if params[:pinboard]
     @pin_property = Bank.new(pinboard_params)
     @pin_property.user_id = params[:id]
    respond_to do |format|
      if @pin_property.save
        format.html { 
          redirect_to pinboards_path, notice: 'Picture is successfully added in your friend pinboard.' 
        }
      else
        format.html {  render :template => "/friendships/assign_picture_to_user"}
      end
    end
  else
    render :template => "/friendships/assign_picture_to_user"
  end
end

def change_user_status
  @user = User.find(params[:id])
  @user.status = false
  @user.save
  redirect_to "/block_users" ,notice: "#{@user.email} has been blocked."
end

  def update
    respond_to do |format|
      if @pin_property.update(idea_params)
        format.html { redirect_to pinboards_path, notice: 'PinProperty was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin_property }
      else
        format.html { render :edit }
        format.json { render json: @pin_property.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    if @pin_property.user != current_user
      respond_to do |format|
        format.html { redirect_to pinboard_path, alert: 'You are not authorized to destroy this pinboard.' }
        format.json { head :no_content }
      end
      return false
    end
    @pin_property.destroy
    respond_to do |format|
      format.html { redirect_to pinboards_url, notice: 'PinProperty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
     def set_pinboard
      @pin_property = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pinboard_params
      params.require(:pinboard).permit(:name, :description, :picture)
    end
end

user_app/app/helpers/application_helper.rb
module ApplicationHelper
end

user_app/app/helpers/banks_helper.rb
module BanksHelper
end

user_app/app/views/banks/_form.html.erb
<%= form_for(:pinboard) do |f| %>
  <% if @pin_properties.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin_properties.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin_properties.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :name, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :picture, :class => "col-sm-2 control-label margin-top" %>
      <div class="col-sm-10">
        <%= f.file_field :picture, :class => "form-control margin-top" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <br/>
        <p class="pull-right"><%= f.submit :class => "btn btn-primary" %></p>
      </div>
    </div>
<% end %>

user_app/app/views/banks/block_users.html.erb
<h3>User Details</h3>

<table border=4>
  <thead>
  <tr>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
           <td><%= user.email %></td>

         <td><%= link_to "Block User", "/change_user_status/#{user.id}" %></td>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

user_app/app/views/banks/create.html.erb
<h1>Pinboards#create</h1>
<p>Find me in app/views/pinboards/create.html.erb</p>

user_app/app/views/banks/edit.html.erb
<h1>Pinboards#edit</h1>
<p>Find me in app/views/pinboards/edit.html.erb</p>

user_app/app/views/banks/index.html.erb
<br/>
<%#if current_user.pin_properties.present?%>

<%# @pin_properties.in_groups_of(3) do |group| %>
    <div class="row">
      <% #group.compact.each do |pinboard| %>
          <div class="col-md-4">
                <%#= image_tag pinboard.picture, width: '100%' if pinboard.picture.present?%>
                <h4 style="color: #2196f3;"><%#= pinboard.name %></h4>
            <%#= pinboard.description %>
         # </div>
      <% #end %>
    </div>
<%# end %>
<%# end %>

user_app/app/views/banks/new.html.erb
<h3>New PinProperty</h3>

<%= render 'form' %>

user_app/app/views/banks/show.html.erb
<div class="row">
  <div class="col-md-9">
    <%= image_tag(@pin_property.picture_url, width: '100%') if @pin_property.picture.present? %>
  </div>

  <div class="col-md-3">
    <br/>
    <p>
      <b>Name: </b><%= @pin_property.name %>
      <% if current_user == @pin_property.user %>
          <%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_pinboard_path(@pin_property) %>
          <%= link_to "<i class='glyphicon glyphicon-trash text-danger'></i>".html_safe, @pin_property, data: { confirm: 'Are you sure?' }, method: :delete %>
      <% end %>
    </p>
    <p><b>Description: </b><%= @pin_property.description %></p>
  </div>
</div>

user_app/app/views/banks/users_list.html.erb
<h3>Friend Lists</h3>

<table border=4>
  <thead>
  <tr>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
           <td><%= user.email %></td>        
          <td>
            <%# if user.friends.present?%>
             <!--<p>Already assigned</p>-->
            <%#else%>
            <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
            <%#end%>
          </td>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

user_app/app/views/banks/view_my_profile.html.erb
<h3> My Profile </h3>
<p>Email: <%=current_user.email %></p>

<h3>Your Friends</h3>
<ul>
  <% for friendship in current_user.friendships %>
  <li class="friend_info">
    <%= h friendship.friend.email %>
    
    <div class="button">
    <%#= link_to "View Profile", "#{friendship_path}?id=#{friendship.friend.id}" %>
        <%#= link_to "View Profile", "#{/show_user_profile/:id =>friendship.friend.id}" %>
        <%= link_to "View Profile", "show_user_profile/#{friendship.friend.id}" %>
    </div>
    <div class="button">
        <%= link_to "remove", "delete/#{friendship.friend.id}" %>
    </div>
  </li>
  <% end %>  
</ul>

<div class="find_friend">
<div class="button">
  <%= link_to "Find Friends", get_all_user_details_path %>
</div>
</div>

user_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Info</title>
  <!--<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">-->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.1/paper/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">User App</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><a href="/banks">UserList</a></li>
        <li ><%= link_to 'New Bank', new_bank_path %></li>
        <li ><%= link_to 'Add Friend', get_all_user_details_path %></li>
          <li ><%= link_to 'User List', block_users_path %></li>
        <% end %>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
            Logged in as
            <strong><%= current_user.email %></strong>.
            <%= link_to 'View Profile', view_my_profile_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
      <br/>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <br/>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>

<footer>
  <div class="container">
    
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>